Help 8

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,6 +1,7 @@
 #!/bin/sh
 
 ORACLE_URL="https://download.oracle.com/otn_software/linux/instantclient/1922000/instantclient-basic-linux.x64-19.22.0.0.0dbru.zip"
+ORACLE_SDK_URL="https://download.oracle.com/otn_software/linux/instantclient/1922000/instantclient-sdk-linux.x64-19.22.0.0.0dbru.zip"
 
 arrow() {
   sed -u 's/^/-----> /'
@@ -50,8 +51,32 @@ if [ "$?" != "0" ]; then
 fi
 rm "instantclient.zip"
 
-echo "Copying files" | indent
-mkdir -p $BUILD_DIR/.heroku/oracle/instantclient_19_22
-cp -r "instantclient_19_22" $BUILD_DIR/.heroku/oracle/instantclient_19_22
-
 echo "Done" | indent
+
+# SDK EXTENSION
+echo "Installing Oracle Instant Client SDK" | arrow
+cd $BUILD_DIR
+cd vendor
+mkdir sdk
+
+cd sdk
+echo "Downloading" | indent
+code=$(curl "$ORACLE_SDK_URL" -L --silent --fail --retry 5 --retry-max-time 15 -o instantclientsdk.zip --write-out "%{http_code}")
+if [ "$code" != "200" ]; then
+  echo "Unable to download Instant Client SDK: $code" | indent && exit 1
+fi
+
+echo "Unpacking" | indent
+unzip -q "instantclientsdk.zip"
+if [ "$?" != "0" ]; then
+  echo "Failed to unpack Instant Client SDK" | indent && exit 1
+fi
+
+rm "instantclientsdk.zip"
+
+echo "Moving SDK files" | indent
+mv instantclient_19_22/sdk/include/* ../oracle/instantclient_19_22/
+cd ..
+rm -r sdk
+
+echo "Done!" | arrow
